"use client";

import { Avatar } from "@/components/site-chrome";
import { api, mediaSrc, relativeTime } from "@/lib/api";
import type { FeedPost } from "@aura/shared";
import Link from "next/link";
import { useState } from "react";
import { useSession } from "./session-provider";

export function PostCard({ post, onDeleted, onChanged }: { post:FeedPost;onDeleted?:(id:string)=>void;onChanged?:()=>void }) {
  const {user}=useSession();const [liked,setLiked]=useState(post.currentUserLiked);const [likes,setLikes]=useState(post.likeCount);const [busy,setBusy]=useState(false);const own=user?.id===post.userId;
  async function toggleLike(){if(busy)return;const next=!liked;setLiked(next);setLikes((v)=>Math.max(0,v+(next?1:-1)));setBusy(true);try{await api(`/v1/posts/${post.id}/like`,{method:next?"POST":"DELETE"});}catch{setLiked(!next);setLikes((v)=>Math.max(0,v+(next?-1:1)));}finally{setBusy(false);}}
  async function repost(){try{await api(`/v1/posts/${post.id}/repost`,{method:"POST",body:JSON.stringify({})});onChanged?.();}catch{/* UI remains stable; duplicate plain repost is idempotent at the product level. */}}
  async function remove(){if(!confirm("Delete this post?"))return;await api(`/v1/posts/${post.id}`,{method:"DELETE"});onDeleted?.(post.id);}
  const Context=({label,item}:{label:string;item:FeedPost["originalPost"]})=>item?<Link href={`/post/${item.id}`} className="mb-3 block rounded-xl border border-white/[.07] p-3 text-xs text-zinc-500 hover:bg-white/[.025]"><span>{label} @{item.author.username}</span><p className="mt-1 line-clamp-2 text-zinc-400">{item.body||"Media post"}</p></Link>:null;
  return <article className="border-b border-white/[.07] p-4 transition hover:bg-white/[.012] sm:p-5"><div className="flex gap-3"><Link href={`/profile/${post.author.username}`}><Avatar user={post.author}/></Link><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><Link href={`/profile/${post.author.username}`} className="min-w-0"><span className="block truncate text-sm font-medium text-zinc-100">{post.author.displayName}{post.author.isVerified&&<span className="ml-1 text-violet-300">◆</span>}</span><span className="block truncate text-xs text-zinc-600">@{post.author.username} · {relativeTime(post.createdAt)}</span></Link><details className="relative ml-auto"><summary className="cursor-pointer list-none rounded-full px-2 text-zinc-600 hover:text-white" aria-label="Post actions">•••</summary><div className="absolute right-0 z-10 mt-2 w-40 rounded-xl border border-white/10 bg-zinc-950 p-1 shadow-xl">{own&&<button onClick={remove} className="w-full rounded-lg px-3 py-2 text-left text-xs text-red-300 hover:bg-white/[.06]">Delete post</button>}<button onClick={()=>navigator.clipboard.writeText(`${location.origin}/post/${post.id}`)} className="w-full rounded-lg px-3 py-2 text-left text-xs text-zinc-300 hover:bg-white/[.06]">Copy link</button></div></details></div><div className="mt-3"><Context label="Reposted from" item={post.originalPost}/><Context label="Replying to" item={post.parentPost}/>{post.body&&<p className="whitespace-pre-wrap break-words text-[15px] leading-6 text-zinc-200">{post.body}</p>}{post.mediaUrl&&<img src={mediaSrc(post.mediaUrl)??""} alt="Post media" className="mt-3 max-h-[560px] w-full rounded-2xl border border-white/[.08] object-cover"/>}</div><div className="mt-4 grid grid-cols-4 text-xs text-zinc-600"><button onClick={toggleLike} disabled={busy} className={`rounded-lg py-2 text-left hover:text-pink-300 ${liked?"text-pink-300":""}`} aria-label={liked?"Unlike post":"Like post"}>♡ <span>{likes||""}</span></button><Link href={`/post/${post.id}`} className="rounded-lg py-2 hover:text-sky-300" aria-label="View comments">○ <span>{post.commentCount||""}</span></Link><button onClick={repost} className="rounded-lg py-2 hover:text-emerald-300" aria-label="Repost">↻ <span>{post.repostCount||""}</span></button><button onClick={()=>navigator.clipboard.writeText(`${location.origin}/post/${post.id}`)} className="rounded-lg py-2 text-right hover:text-white" aria-label="Copy post link">↗</button></div></div></div></article>;
}
